In [2]:
print("Samartha")


Samartha


In [2]:
import numpy as np
arr1 = np.array([4,2,8,8,9])
print(arr1)


[4 2 8 8 9]


In [3]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [4]:
#Creating a 3-D Array using 2-D values\
arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [5]:
#Printing array dimensions 
print("No. of dimensions :",arr2.ndim)

No. of dimensions : 2


In [7]:
#Printing array shape
print("Shape of array :",arr2.shape)


Shape of array : (2, 3)


In [8]:
print("Size of array :",arr2.size)

Size of array : 6


In [5]:
#Creating an array from list with float type
import numpy as np
b = np.array([[1,2,3],[4,5,6]], dtype = 'float')
print("Array created using passed list is:\n", b)

Array created using passed list is:
 [[1. 2. 3.]
 [4. 5. 6.]]


In [6]:
#Creating an array from tuple
a = np.array((1,2,3,4))
print("Array created from tuple is:\n",a)

Array created from tuple is:
 [1 2 3 4]


In [7]:
#Creating a 3*4 array with all zeros
c = np.zeros((3,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
t = np.full((2,2), 4, dtype = 'complex')
print("Array complex type is:\n",t)

Array complex type is:
 [[4.+0.j 4.+0.j]
 [4.+0.j 4.+0.j]]


In [12]:
#Creating an array with random values 
a = np.random.random((4,4))
print("Array with random values is:\n",a)

Array with random values is:
 [[0.47711212 0.97451981 0.20127889 0.88439741]
 [0.98701716 0.03498091 0.17522247 0.23582361]
 [0.65489801 0.15160765 0.31907197 0.18340112]
 [0.16473516 0.40249569 0.84681322 0.07287633]]


In [14]:
#Create a sequence of integers from 0 to 30 with steps of 5
b = np.arange(0,30,5)
print(b)


[ 0  5 10 15 20 25]


In [17]:
#Create a sequnce of 11 values in range from 0 to 5
b= np.linspace(0,4,11)
print(b)

[0.  0.4 0.8 1.2 1.6 2.  2.4 2.8 3.2 3.6 4. ]


In [27]:
#Reshaping a 3*4array into a 2,2,33 array
a = np.array([[1,2,3,5],
            [4,5,6,8],[1,2,3,4]])

b = a.reshape(2,2,3)
print(a)
print(b)

[[1 2 3 5]
 [4 5 6 8]
 [1 2 3 4]]
[[[1 2 3]
  [5 4 5]]

 [[6 8 1]
  [2 3 4]]]


In [31]:
#Flatten array 
u = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = u.flatten()
print(b)
print(b.ndim)
print(u.ndim)

[1 2 3 4 5 6 7 8 9]
1
2


In [35]:
#Create an array of given shape and populate it with random samples and all the values are between [0,1]
a = np.random.rand(2,3)
print(a)
b = np.random.rand(5)
print(b)

[[0.78477268 0.1079287  0.77383308]
 [0.29179039 0.06116899 0.30102028]]
[0.28866408 0.85927881 0.39782708 0.27554162 0.73207851]


In [36]:
#Generating 5 random integers between 2 and 4
a = np.random.randint(2,4,5)
print(a)

[3 2 3 3 2]


In [41]:
#np.maatrix-Returns a matrix from an array like object
a = np.matrix(np.arange(12).reshape((3,4)))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:
#Python programs to demonanstrate binary operators in numpy
#Addition of arrays 
import numpy as np
a = np.array([[1,2,]
              ,[4,5,]])
b = np.array([[3,4,],
              [6,7,]])
print(a)
print(b)
print("Array sum is:\n",a+b)


[[1 2]
 [4 5]]
[[3 4]
 [6 7]]
Array sum is:
 [[ 4  6]
 [10 12]]


In [7]:
#Multiplication of arrays
c = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])
print("Multiplication of array is:\n",c*b)

Multiplication of array is:
 [[ 1  4]
 [ 9 16]]


In [8]:
#Multiplicatiojn of matrices
c = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])
print("Matrix multiplication is:",c.dot(b))

Matrix multiplication is: [[ 7 10]
 [15 22]]
